name: Docker Mirror Speed Test

on:
  schedule:
    - cron: "0 0 * * *" # 每天凌晨0点触发
  workflow_dispatch: # 手动触发

jobs:
  test-mirrors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Extract Docker mirror links
        id: extract_links
        run: |
          #!/bin/bash
          # 提取README.md文件中Docker镜像源链接
          markdown_file="README.md"
          # 使用grep提取所有Docker类型链接，并去除url标签
          docker_mirrors=$(grep -oP '(?<=Docker).+?(https://\S+)' "$markdown_file" | grep -oP 'https://\S+' | tr '\n' ',')
          echo "Docker mirrors extracted: $docker_mirrors"
          echo "docker_mirrors=$docker_mirrors" >> $GITHUB_ENV

      - name: Test Docker mirror speed
        id: test_speed
        run: |
          #!/bin/bash
          # 切分环境变量中的镜像源
          IFS=',' read -r -a mirrors <<< "${{ env.docker_mirrors }}"
          # 测试每个镜像源的下载速度
          for mirror in "${mirrors[@]}"; do
            echo "Testing mirror: $mirror"
            # 使用docker pull命令测试下载速度，使用较大的镜像
            image="pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime"
            start_time=$(date +%s%3N)
            docker pull --quiet "$mirror/$image"
            end_time=$(date +%s%3N)
            # 获取镜像大小
            image_size=$(docker inspect --format='{{.Size}}' "$mirror/$image" 2>/dev/null)
            if [[ $? -eq 0 ]]; then
              # 计算下载速度
              duration=$((end_time - start_time))
              speed=$(echo "scale=2; $image_size / $duration / 1024 / 1024" | bc) # 速度单位为MB/s
              echo "Mirror $mirror speed: $speed MB/s"
              # 将速度信息存储到文件中
              echo "$mirror,$speed" >> mirror_speeds.csv
            else
              echo "Failed to inspect image $mirror/$image"
              echo "$mirror,Failed" >> mirror_speeds.csv
            fi
          done

      - name: Update README.md with speed information
        run: |
          #!/bin/bash
          # 更新README.md文件中的速度信息
          markdown_file="README.md"
          while IFS=, read -r mirror speed; do
            # 替换对应的速度信息
            sed -i "s|($mirror).*|$mirror | $speed MB/s|" "$markdown_file"
          done < mirror_speeds.csv

      - name: Commit and push changes
        run: |
          #!/bin/bash
          # 提交并推送README.md文件的更改
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add "$markdown_file"
          git commit -m "Update Docker mirror speeds"
          git push
